<?php

namespace Tests\Unit;

use App\Models\AccountType;
use App\Services\AccountType\AccountTypeService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AccountTypeServiceTest extends TestCase
{
    use RefreshDatabase;

    private AccountTypeService $accountTypeService;

    public function setUp(): void
    {
        parent::setUp();
        $this->accountTypeService = new AccountTypeService();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated
    }

    public function testGetAccountTypesShouldReturnAllAvailableType()
    {

        $response = $this->accountTypeService->getAccountTypes();

        $this->assertCount(count($response), AccountType::all());
    }
}
